name: Build & Deploy

on:
  push:
    branches:
      - staging
      - main

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
  
    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_MONGO_URI: ${{ secrets.MONGO_URI }}
        envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
        envkey_JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
        fail_on_empty: true

    - name: Install dependencies
      run: npm ci

    - name: Build App
      run: npm run build

    - name: Deploy App
      uses: serverless/github-action@v3.1
      with:
        args: deploy --stage ${{ github.ref_name }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
